### ISSUE TITLE
Gulp watch not running/errors

### ISSUE THREAD

**Issue by JamiesonRoberts** [ArcaneDigital/our-faces#1]
**Please note, this is in the wireframe branch currently**

I keep receiving an error when running gulp watch (attached below) that looks like the following.

gulp watch
[19:57:54] Using gulpfile ~/Websites/our-faces/client/gulpfile.js
[19:57:54] Starting 'watch'...
2015-05-16 19:57 gulp[58823](FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-05-16 19:57 gulp[58823](FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
[19:57:54] Finished 'watch' after 15 ms
2015-05-16 19:57 gulp[58823](FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch EMFILE
    at exports._errnoException (util.js:746:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1161:26)

Initial searching seems to suggest that its not liking the number of files its watching, but is a fairly succinct watch task. Could be due to ember running grunt and watching files as well as using gulp for front end development.

Watch Task is as follows
// Watch Files For Changes
gulp.task('watch', function () {
    gulp.watch('app/scripts/**/*.js', ['lint', 'scripts']);
    gulp.watch('app/styles/**/*.scss', ['styles']);
});

**Comment by jorbascrumps** [comment]
All you're doing is running `gulp watch`?

**Comment by JamiesonRoberts** [comment]
Yep, I can do the individual tasks on their own, but when I do the watch it throws an error.

I just tried doing the gulp watch without the ember server running and it works fine, so it has to do with the number of files being watched at one time. I wonder if it might be better to try and do a grunt task or modify what the built in task is doing. @iamchristopher

**Comment by JamiesonRoberts** [comment]
So I lied @iamchristopher, its not grunt, they are using broccoli.js https://github.com/broccolijs/broccoli

I'm going to try playing around with that, see if I can either disable it or better yet, get it to do the sass compiling and js moving etc, so that you just have to run ember server and it does the rest!

**Comment by jorbascrumps** [comment]
We should get some tests going on more machines as I was able to run the task without issue.

**Comment by JamiesonRoberts** [comment]
@iamchristopher It could just be my ancient laptop not wanting to track that many files. I've since blown away the gulp stuff and I'm trying out a native solution based off of reading through the app stuff. I think I might have it working now.
